blank_issues_enabled: false
contact_links:
  - name: conda-store-ui documentation
    url: https://conda-incubator.github.io/conda-store-ui/
    about: Check out the conda-store-ui documentation
  - name: jupyterlab-conda-store issue tracker
    about: Did you find a bug or want to make a suggestion? Open an issue on our tracker.
    url: https://https://github.com/conda-incubator/jupyterlab-conda-store/issues/new/choose
