name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository ðŸ›Ž'
        uses: actions/checkout@v4

      - name: 'Base Setup ðŸ› '
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: 'Install dependencies ðŸ“¦'
        run: python -m pip install -U jupyterlab~=3.1

      - name: 'Lint the extension ðŸ§¹'
        run: |
          set -eux
          jlpm
          jlpm run lint:check

      - name: 'Test the extension ðŸ§ª'
        run: |
          set -eux
          jlpm run test --passWithNoTests

      - name: 'Build the extension ðŸ—'
        run: |
          set -eux
          python -m pip install .[test]

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-conda-store.*OK"
          python -m jupyterlab.browser_check

      - name: 'Package the extension ðŸ“¦'
        run: |
          set -eux

          pip install build
          python -m build

      - name: 'Upload extension packages ðŸ“¤'
        uses: actions/upload-artifact@v3
        with:
          name: extension-artifacts
          path: dist/
          if-no-files-found: error

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository ðŸ›Ž'
        uses: actions/checkout@v4

      - name: 'Install Python ðŸ'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: 'Download extension packages ðŸ“¤'
        uses: actions/download-artifact@v3
        with:
          name: extension-artifacts

      - name: 'Install and Test ðŸ§ª'
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)

          pip install "jupyterlab~=3.1" jupyterlab_conda_store*.whl


          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-conda-store.*OK"
          python -m jupyterlab.browser_check --no-chrome-test

  integration-tests:
    name: Integration tests
    needs: build
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

    steps:
      - name: "Checkout repository ðŸ›Ž"
        uses: actions/checkout@v4

      - name: "Base Setup"
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: 'Download extension packages ðŸ“¤'
      uses: actions/download-artifact@v3
      with:
        name: extension-artifacts

      - name: "Install the extension"
        run: |
          set -eux
          python -m pip install "jupyterlab~=3.1" jupyterlab_conda_store*.whl

      - name: "Install dependencies"
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: jlpm install

      - name: "Set up browser cache"
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/pw-browsers
          key: ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}

      - name: "Install browser"
        run: jlpm playwright install chromium
        working-directory: ui-tests

    # - name: Execute integration tests
    #   working-directory: ui-tests
    #   run: |
    #     jlpm playwright test

    # - name: Upload Playwright Test report
    #   if: always()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: jupyterlab_conda_store-playwright-tests
    #     path: |
    #       ui-tests/test-results
    #       ui-tests/playwright-report
